#!/bin/bash

net2_url=net2.sharif.edu
login_page_url=https://net2.sharif.edu/login
conenction_check_url=google.com
configs_file="$HOME/.local/share/snc"
favorite_ssids_file="$configs_file/ssids.conf"
username_password_file="$configs_file/username_password.conf"


load_username_password(){
        if test -s $username_password_file;
        then
                username=$(awk '/username/ {split($1,a,":"); print a[2]}' $username_password_file)
                encrypted_password=$(awk '/password/ {split($1,a,":"); print a[2]}' $username_password_file)
                password=$(echo $encrypted_password | openssl enc -aes-128-cbc -iter 29 -a -d -salt -pass pass:asdffdsa)
	else
                echo "Please first set your net2 username and password using \`config\` command."
		echo "See --help or -h for more"
                exit 1
        fi
}

load_favorite_ssids(){
        if test -s $favorite_ssids_file;
        then
                online_favorite_ssids=$(nmcli device wifi list | grep -wi -f $favorite_ssids_file | cut -d '*' -f 2 | awk '{print $2}')
		ssids=($online_favorite_ssids)
	else
                echo "There is no modem id in your list. Add one with \`newmodem\` command."
                echo "See --help or -h for more."
		exit 1
        fi
}

login(){
	ssid="$1"
	connection=$(ping -q -w 5 -c 1 $net2_url > /dev/null 2>&1 && echo 1 || echo 0)
	if [ $connection -eq 1 ];
	then
		if test -z $ssid;
		then
			echo "Wire Connection; check"
		else
			echo "Connected to $ssid"
		fi
		load_username_password
		echo "Loging in as $username"
		curl -Ls -d "username=$username&password=$password" -X POST $login_page_url > /dev/null 2>&1
		connection=$(ping -q -w 2 -c 1 $conenction_check_url > /dev/null 2>&1 && echo 1 || echo 0)
		if [ $connection -eq 1 ];
		then
			echo "Successfully logged in"
			exit 0
		else
			echo "Login Failed"
		fi
	else
		echo "Seems like there is a problem. Make sure cable is connected"
	fi
}


connect_to_specific_modem(){
	echo "Connecting to $ssid"
	nmcli device wifi connect $ssid > /dev/null 2>&1
	login $1
	echo "I Couldn't find any of your modems around here"
        echo "Make sure you are close to one of your modems in the list or add new one"
	exit 1
}

try_connecting_to_given_modem(){
        connect_to_specific_modem $1
}


try_connecting_to_favorite_modems(){
	load_favorite_ssids
	for ssid in "${ssids[@]}";
        do
		echo $ssid
		connect_to_specific_modem "$ssid"	
        done
}

connect(){
	nmcli radio wifi on
	# sleep 1
	# nmcli device wifi rescan > /dev/null 2>&1

	if test -z $1;
	then
		try_connecting_to_favorite_modems
	else
		try_connecting_to_given_modem $1
	fi
}

add_modem_ssid(){
	if [ -z $2 ];
	then
		echo "You should give modem ssid"
		echo "See --help' or -h"
		exit 1
	else
		new_ssids=($@)
		for (( i=1; i<=($#-1); i++ ));
		do
			echo "${new_ssids[$i]}" | tee -a $favorite_ssids_file > /dev/null
		done
	fi
}

configure(){
	username=$1
	password=$2
	if [ -z $1 ];
	then
		read -p "sharif-id username:" username
		read -s -p "sharif-id password:" password
		echo
	elif [ -z $2 ];
	then
		echo "$1 assumed as your net2 username"
		read -s -p "sharif-id password:" password
	fi

	encrypted_password=$(echo $password | openssl enc -aes-128-cbc -iter 29 -a -salt -pass pass:asdffdsa)
	echo -e "username:$username\npassword:$encrypted_password" | tee $username_password_file > /dev/null
}

show_favorite_modems(){
	if test -s $favorite_ssids_file;
	then
		cat $favorite_ssids_file
	else
		echo "There is no modem id in your list. Add one with newmodem command."
		echo "See --help or -h"
		exit 1
	fi
}

remove_modem_ssid(){
	ssids=$(echo $@ | awk '{gsub(" ","\\|",$0); print $0}')
	grep -wi -v "$ssids" $favorite_ssids_file >> tmp.txt
	mv tmp.txt $favorite_ssids_file
}

status(){
	ping -q -w 5 -c 1 $conenction_check_url > /dev/null 2>&1 && echo -e '\033[92m'connected || echo -e '\033[91m'no connection

}

help(){
	echo " \`snc\` connects sharif modems and log you in to net2 in an EZ way!"
	echo 
	echo "	usage: snc { COMMAND }  	snc does the rest :)"
  	echo

	echo "commands:"
	echo "  config | co                     saves your net2 username and password."
        echo "  config | co <username> <password> same."
	echo "  connect | c                     connects to one of the modems you added "
        echo "                                  before that has strongest signal"
	echo "                                  and then does the job with net2.sharif.edu."
        echo "  connect | c <moddem>            connects to specific modem and goes on."
	echo "  newmodem | n <modem>...         adds a new modem id to your list."
	echo "  remove | r <modem>...           removes a modem id from list."
	echo "  show | sh                       shows modem ssids you added before."
	echo "  status | s                      shows connection status."
	echo 

	echo "arguments:"
	echo "  --help | -h                     shows this usefull help!"
	exit 0
}

case $1 in
        connect | c)
		connect "$2"
		;;
	connectwire | cw)
		login
		;;
        config | co)
		configure $2 $3 
                ;;
        newmodem | n)
                add_modem_ssid $@
                ;;
	remove | r)
		remove_modem_ssid $@
		;;
	show | sh)
		show_favorite_modems
		;;
	status | s)
		status
		;;
	--help | -h)
		help
                ;;
	*)
		echo "Find what you want"
		help
		;; 
esac
